package cz.mg.projectexplorer.components.extensions;

import cz.mg.compiler.Location;
import cz.mg.compiler.entities.resources.InternalFile;
import cz.mg.compiler.tasks.TaskError;
import cz.mg.projectexplorer.graphics.Highlight;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.LinkedList;


public class TaskErrorPanel extends javax.swing.JPanel {
    private static final Color ERROR_HIGHLIGHT_COLOR = new Color(255, 160, 160);
    
    public TaskErrorPanel(TaskError error) {
        initComponents();
        jTextAreaException.setText(error.getException().getText());
        jPanelCode.add(new CodeArea(
            loadCode(error.getException().getErrorMessage().getLocation().getName()),
            new Highlight[]{createErrorHighlight(error)}
        ));
    }
    
    private String[] loadCode(String path){
        try {
            BufferedReader reader = new BufferedReader(new InputStreamReader(new InternalFile(null, null, path).getStream()));
            LinkedList<String> lines = new LinkedList<>();
            String line;
            while((line = reader.readLine()) != null) lines.add(line);
            String[] linesArray = new String[lines.size()];
            lines.toArray(linesArray);
            return linesArray;
        } catch (IOException ex) {
            return new String[0];
        }
    }
    
    private Highlight createErrorHighlight(TaskError error){
        Location location = error.getException().getErrorMessage().getLocation();
        return new Highlight(
            location.getRowBegin(),
            location.getColumnBegin(),
            location.getColumnEnd(),
            ERROR_HIGHLIGHT_COLOR
        );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelCode = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaException = new javax.swing.JTextArea();

        setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane1.setDividerLocation(128);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanelCode.setLayout(new java.awt.GridLayout());
        jSplitPane1.setLeftComponent(jPanelCode);

        jTextAreaException.setEditable(false);
        jTextAreaException.setColumns(20);
        jTextAreaException.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextAreaException.setRows(5);
        jTextAreaException.setTabSize(4);
        jScrollPane2.setViewportView(jTextAreaException);

        jSplitPane1.setRightComponent(jScrollPane2);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCode;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaException;
    // End of variables declaration//GEN-END:variables
}
